backend:
  name: git-gateway
  branch: master

local_backend: true

publish_mode: editorial_workflow

media_folder: "/src/images"

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "index"
        name: "index"
        file: "src/content/index.md"
        fields:
          - { label: "Template", name: "template", widget: "select", options: ["other"] }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Image", name: "image", widget: "image", required: false }
          - { label: "Image alt text", name: alttext, widget: string }
          - { label: "Fore image", name: "foreimage", widget: "image", required: false }
          - { label: "Fore image alt text", name: forealttext, widget: string }          
          - label: Features
            name: features
            widget: list
            fields:
              - { label: "Features title", name: title, widget: string }
              - { label: "Features subtitle", name: subtitle, widget: string, required: false }
              - { label: "Features image", name: image, widget: image }
              - { label: "Features image alt text", name: alttext, widget: string }
              - label: Text
                name: text
                widget: list
                fields:
                  - { label: "Feature text", name: text, widget: "string" }            
          - label: Section
            name: section
            widget: list
            fields:
              - { label: "Section title", name: title, widget: string }
              - { label: "Section subtitle", name: subtitle, widget: string, required: false }
              - { label: "Section description", name: description, widget: string }
              - { label: "Section image", name: image, widget: image }
              - { label: "Section image alt text", name: alttext, widget: string }
              - { label: "Section image placement", name: "placement", widget: "select", options: ["card", "left", "right"] }
              - { label: "Button link", name: btnlink, widget: string, required: false }
              - { label: "Button colour", name: "btncolour", widget: "select", options: ["ficon-cics", "ficon-det", "ficon-eden", "ficon-iet", "ficon-il", "ficon-m4", "ficon-rob", "ficon-sl", "ficon-tb", "ficon-ue", "ficon-ug", "ficon-usi"], required: false }